-- HEI Talk sessions updated from official schedule (Jul 2026)
DELETE FROM public.registrations;
DELETE FROM public.events;

SELECT setval(pg_get_serial_sequence('public.events', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('public.registrations', 'id'), 1, false);

INSERT INTO public.events (name, description, date, start_time, end_time, address, slug, capacity)
VALUES
  ('Why Halal Economy in Indonesia''s D-8 Chairmanship', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Special Staff to The Minister of Foreign Affairs for Strengthening Multilateral Issue Policy</li><li>Director of Inter-Regional Negotiations and International Organizations, Ministry of Trade</li><li>Director of Business and Entrepreneurship, KNEKS</li><li>Deputy Chairman for Multilateral Diplomacy Indonesian Chamber of Commerce and Industry (KADIN)</li></ol><p><strong>Moderator:</strong> Ministry of Foreign Affairs</p>', '2026-07-08', '13:00:00', '15:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'why-halal-economy-in-indonesias-d-8-chairmanship', 20),
  ('Driving Social Impact through Islamic Ultra Micro Financing for Rural and Women', '<p><strong>Speakers / Panelists:</strong></p><ol><li>CEO of PT. PNM, Indonesia</li><li>CEO of btpnsyariah</li><li>Dr. Muhammad Amjad Saqib – Founder & Chairman of Akhuwat, Pakistan</li></ol><p><strong>Moderator:</strong> Director of Center for Islamic Economics and Business (PEBS), Universitas Indonesia</p>', '2026-07-08', '15:30:00', '16:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'driving-social-impact-through-islamic-ultra-micro-financing', 20),
  ('Driving the Future of Global Halal Trade: Strategic Synergies Between Indonesia, Pakistan and Iran', '<p><strong>Speakers / Panelists:</strong></p><ol><li>His Excellency Ambassador of Pakistan</li><li>His Excellency Ambassador of Iran</li><li>COO of Sinarmas Group</li></ol><p><strong>Moderator:</strong> Head of CSED INDEF</p>', '2026-07-09', '09:00:00', '10:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'driving-the-future-of-global-halal-trade-pakistan-iran', 20),
  ('Halal Critical Raw Material Innovation', '<p><strong>Speakers / Panelists:</strong></p><ol><li>IPB University</li><li>Direktur Produksi PT Phapros Tbk</li><li>Direktur Investasi dan Ekonomi Kreatif, Kementerian Luar Negeri</li></ol><p><strong>Moderator:</strong> Executive Director, Center of Reform on Economics (CORE) Indonesia</p>', '2026-07-09', '10:30:00', '12:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'halal-critical-raw-material-innovation', 20),
  ('BSI SESSION (TBC For Speakers)', '<p><strong>Speakers / Panelists:</strong></p><ol><li>TBC (To Be Confirmed)</li></ol>', '2026-07-09', '13:00:00', '14:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'bsi-session', 20),
  ('Driving the Future of Global Halal Trade: Strategic Synergies between Indonesia, Türkiye and Azerbaijan', '<p><strong>Speakers / Panelists:</strong></p><ol><li>His Excellency Ambassador of Turkiye</li><li>His Excellency Ambassador of Azerbaijan</li><li>President Director, Biofarma</li></ol><p><strong>Moderator:</strong> Director of CIBEST-IPB</p>', '2026-07-09', '16:00:00', '17:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'driving-the-future-of-global-halal-trade-turkiye-azerbaijan', 20),
  ('Unlocking Blended Financing in D-8 through CWLS and CWLD', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Head of Islamic Economy and Finance Department, BI</li><li>Head of Development Capital Market, OJK</li><li>Director of Islamic Social Finance, KNEKS</li><li>Chairman & Independent Director, Social Islami Bank PLC</li></ol><p><strong>Moderator:</strong> Mhd. Iqbal Balative (DJPPR)</p>', '2026-07-10', '09:30:00', '11:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'unlocking-blended-financing-in-d-8-through-cwls-and-cwld', 20),
  ('Driving the Future of Global Halal Trade & Economy Intra D-8: Lesson Learn From Malaysia, dan Bangladesh', '<p><strong>Speakers / Panelists:</strong></p><ol><li>His Excellency Ambassador of Malaysia</li><li>His Excellency Ambassador of Nigeria</li><li>Group CEO ParagonCorp / Biofarma</li></ol><p><strong>Moderator:</strong> Head of CSED INDEF</p>', '2026-07-10', '13:30:00', '15:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'driving-the-future-of-global-halal-trade-malaysia-bangladesh', 20),
  ('Developing Muslim-Friendly Tourism for Sustainable Economic Growth in D-8', '<p><strong>Speakers / Panelists:</strong></p><ol><li>CEO & Founder Crescentrating</li><li>Expert Staff to the Minister for Digital Transformation and Tourism Innovation, Ministry of Tourism</li><li>Managing Director Artotel Group</li></ol><p><strong>Moderator:</strong> Umar Aditiawarman, Ph.D</p>', '2026-07-10', '16:00:00', '17:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'developing-muslim-friendly-tourism-for-sustainable-economic', 20),
  ('Reviving Investment & Business Ethic to redefine future Halal Intelligent', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Inspigo</li><li>Muslim Capital Club</li><li>Muslim Capital Club</li></ol><p><strong>Moderator:</strong> Proposed Moderator</p>', '2026-07-10', '18:30:00', '20:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'reviving-investment--business-ethic-to-redefine-future-halal', 20),
  ('FORUM WAKAF PRODUKTIF : Youth-Powered Development: Mobilising Talent, Faith-Based Finance, and Green Innovation for Shared Prosperity', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Speakers names pending final confirmation</li></ol>', '2026-07-11', '09:00:00', '10:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'forum-wakaf-produktif--youth-powered-development-mobilising', 20),
  ('Halal Youth & Passion as Entrepreneurs (HYPE)', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Chairman of BPP HIPMI</li><li>Chairman Of Banom BPP HIPMI Syariah</li><li>CEO Moria Fund</li></ol><p><strong>Moderator:</strong> Literature & Education Division HIPMI Syariah</p>', '2026-07-11', '10:30:00', '12:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'halal-youth--passion-as-entrepreneurs-hype', 20),
  ('KATADATA : The state of Halal & Sharia Economy in Indonesia : Dari Pasar Terbesar menuju Pusat Ekonomi Syariah Dunia', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Analyst Assistant Manager Katadata Insight Center</li><li>KNEKS</li><li>Ekonom Syariah Senior</li></ol><p><strong>Moderator:</strong> Manager of Databoks by Katadata</p>', '2026-07-11', '13:00:00', '15:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'katadata--the-state-of-halal--sharia-economy-in-indonesia--d', 20),
  ('D-8 in a Changing Global Order: Strengthening Cooperation for a Resilient Future', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Dean of Faculty of Social Sciences, the Indonesian International Islamic University</li><li>Representative from the Ministry of Foreign Affairs of the Republic of Indonesia</li><li>Representative from a D-8 Member State Embassy – (Non-Indonesian Diplomat)</li></ol><p><strong>Moderator:</strong> Rafliansyah – Founder SiPalingHI! Media</p>', '2026-07-11', '16:00:00', '17:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'd-8-in-a-changing-global-order', 20),
  ('BPKH : Haji Muda', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Speakers names pending final confirmation</li></ol>', '2026-07-12', '09:00:00', '10:30:00', 'Senayan Tennis Indoor (2nd Floor)', 'bpkh--haji-muda', 20),
  ('Talent Mapping', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Speakers names pending final confirmation</li></ol>', '2026-07-12', '10:30:00', '12:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'talent-mapping', 20),
  ('Creating Value Through Halal Travel Entrepreneurship', '<p><strong>Speakers / Panelists:</strong></p><ol><li>Bena Kribo</li><li>Islamic Tourism Malaysia: Hurin Ain binti Mohd Noor (Assistant Executive, Industry Development Division)</li><li>Rohayat Binti Din (Senior Director of Sales & Marketing, Lotus Resort & Hotels)</li></ol>', '2026-07-12', '13:00:00', '15:00:00', 'Senayan Tennis Indoor (2nd Floor)', 'creating-value-through-halal-travel-entrepreneurship', 20);
